language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
    - ~/.npm
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile@1
install:
  - greenkeeper-lockfile-update
  - npm ci
before_script:
  - npm prune
script:
  - npm run start
after_success:
  # fetch all tags (semantic-release needs this so it can check last release using git)
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --tags
  - npm run release
after_script:
  - greenkeeper-lockfile-upload