language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
before_install:
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1
install:
  - greenkeeper-lockfile-update
  - npm ci
before_script:
  - npm prune
script:
  - npm run start
after_script:
  - greenkeeper-lockfile-upload